// <auto-generated />
using System;
using AlgoDuck.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoDuck.Migrations
{
    [DbContext(typeof(ApplicationCommandDbContext))]
    [Migration("20251204032927_AddCreatedAtToUserSolution")]
    partial class AddCreatedAtToUserSolution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoDuck.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AmountSolved")
                        .HasColumnType("integer")
                        .HasColumnName("amount_solved");

                    b.Property<Guid?>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<int>("Coins")
                        .HasColumnType("integer")
                        .HasColumnName("coins");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("application_user_pk");

                    b.HasIndex("CohortId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("application_user", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("category_pk");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Cohort", b =>
                {
                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("CohortId")
                        .HasName("cohort_pk");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("cohort", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Contest", b =>
                {
                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<string>("ContestDescription")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("contest_description");

                    b.Property<DateTime>("ContestEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contest_end_date");

                    b.Property<string>("ContestName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contest_name");

                    b.Property<DateTime>("ContestStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contest_start_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("ContestId")
                        .HasName("contest_pk");

                    b.HasIndex("ItemId");

                    b.ToTable("contest", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Difficulty", b =>
                {
                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("difficulty_id");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("difficulty_name");

                    b.HasKey("DifficultyId")
                        .HasName("difficulty_pk");

                    b.ToTable("difficulty", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorLayout", b =>
                {
                    b.Property<Guid>("EditorLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_layout_id");

                    b.Property<Guid>("EditorThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_theme_id");

                    b.Property<Guid>("UserConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_config_id");

                    b.HasKey("EditorLayoutId")
                        .HasName("editor_layout_pk");

                    b.HasIndex("EditorThemeId");

                    b.HasIndex("UserConfigId");

                    b.ToTable("editor_layout", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorTheme", b =>
                {
                    b.Property<Guid>("EditorThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_theme_id");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("theme_name");

                    b.HasKey("EditorThemeId")
                        .HasName("editor_theme_pk");

                    b.ToTable("editor_theme", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("boolean")
                        .HasColumnName("purchasable");

                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.HasKey("ItemId")
                        .HasName("shop_pk");

                    b.HasIndex("RarityId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MessageId")
                        .HasName("message_pk");

                    b.HasIndex("CohortId");

                    b.HasIndex("UserId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("difficulty_id");

                    b.Property<string>("ProblemTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("problem_title");

                    b.HasKey("ProblemId")
                        .HasName("problem_pk");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DifficultyId");

                    b.ToTable("problem", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Purchase", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean")
                        .HasColumnName("selected");

                    b.HasKey("ItemId", "UserId")
                        .HasName("purchases_pk");

                    b.HasIndex("UserId");

                    b.ToTable("purchase", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.PurchasedTestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TestCaseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchasedTestCases");
                });

            modelBuilder.Entity("AlgoDuck.Models.Rarity", b =>
                {
                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rarity_name");

                    b.HasKey("RarityId")
                        .HasName("rarity_pk");

                    b.ToTable("rarity", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("RefreshTokenPrefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_prefix");

                    b.Property<string>("RefreshTokenSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_salt");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("session_pk");

                    b.HasIndex("RefreshTokenPrefix")
                        .HasDatabaseName("session_refresh_prefix_idx");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("UserId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("status_pk");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("tag_pk");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.TestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<string>("CallFunc")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("call_func");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("display");

                    b.Property<string>("DisplayRes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("display_res");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<Guid>("ProblemProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_problem_id");

                    b.HasKey("TestCaseId")
                        .HasName("test_case_pk");

                    b.HasIndex("ProblemProblemId");

                    b.ToTable("test_case", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.TestingResult", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("UserSolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.HasKey("TestCaseId", "UserSolutionId");

                    b.HasIndex("UserSolutionId");

                    b.ToTable("TestingResults");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer")
                        .HasColumnName("current_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_achievement_pk");

                    b.HasIndex("UserId");

                    b.ToTable("user_achievement", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.UserConfig", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dark_mode");

                    b.Property<bool>("IsHighContrast")
                        .HasColumnType("boolean")
                        .HasColumnName("is_high_contrast");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("user_config_pk");

                    b.ToTable("user_config", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolution", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<long>("CodeRuntimeSubmitted")
                        .HasColumnType("bigint")
                        .HasColumnName("code_runtime_submitted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<byte>("Stars")
                        .HasColumnType("smallint")
                        .HasColumnName("stars");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SolutionId")
                        .HasName("user_solution_pk");

                    b.HasIndex("ProblemId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("user_solution", (string)null);
                });

            modelBuilder.Entity("ContestProblem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.HasKey("ProblemId", "ContestId")
                        .HasName("contest_problem_pk");

                    b.HasIndex("ContestId");

                    b.ToTable("contest_problem", (string)null);
                });

            modelBuilder.Entity("HasTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("TagId", "ProblemId")
                        .HasName("has_tag_pk");

                    b.HasIndex("ProblemId");

                    b.ToTable("has_tag", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlgoDuck.Models.ApplicationUser", b =>
                {
                    b.HasOne("AlgoDuck.Models.Cohort", "Cohort")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("user_cohort_ref");

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("AlgoDuck.Models.Cohort", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AlgoDuck.Models.Contest", b =>
                {
                    b.HasOne("AlgoDuck.Models.Item", "Item")
                        .WithMany("Contests")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contest_item_ref");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorLayout", b =>
                {
                    b.HasOne("AlgoDuck.Models.EditorTheme", "EditorTheme")
                        .WithMany("EditorLayouts")
                        .HasForeignKey("EditorThemeId")
                        .IsRequired()
                        .HasConstraintName("editor_layout_editor_theme");

                    b.HasOne("AlgoDuck.Models.UserConfig", "UserConfig")
                        .WithMany("EditorLayouts")
                        .HasForeignKey("UserConfigId")
                        .IsRequired()
                        .HasConstraintName("editor_layout_user_config");

                    b.Navigation("EditorTheme");

                    b.Navigation("UserConfig");
                });

            modelBuilder.Entity("AlgoDuck.Models.Item", b =>
                {
                    b.HasOne("AlgoDuck.Models.Rarity", "Rarity")
                        .WithMany("Items")
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("item_rarity_ref");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("AlgoDuck.Models.Message", b =>
                {
                    b.HasOne("AlgoDuck.Models.Cohort", "Cohort")
                        .WithMany("Messages")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_cohort_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("message_user_ref");

                    b.Navigation("Cohort");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.Problem", b =>
                {
                    b.HasOne("AlgoDuck.Models.Category", "Category")
                        .WithMany("Problems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("problem_category_ref");

                    b.HasOne("AlgoDuck.Models.Difficulty", "Difficulty")
                        .WithMany("Problems")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("problem_difficulty_ref");

                    b.Navigation("Category");

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("AlgoDuck.Models.Purchase", b =>
                {
                    b.HasOne("AlgoDuck.Models.Item", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("item_purchase_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("purchase_user_ref");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.PurchasedTestCase", b =>
                {
                    b.HasOne("AlgoDuck.Models.TestCase", "TestCase")
                        .WithMany("PurchasedTestCases")
                        .HasForeignKey("TestCaseId")
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("PurchasedTestCases")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("TestCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.Session", b =>
                {
                    b.HasOne("AlgoDuck.Models.Session", "ReplacedBySession")
                        .WithMany("InverseReplacedBySession")
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("session_replaced_by_session");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("session_application_user");

                    b.Navigation("ReplacedBySession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.TestCase", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "ProblemProblem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemProblemId")
                        .IsRequired()
                        .HasConstraintName("test_case_problem");

                    b.Navigation("ProblemProblem");
                });

            modelBuilder.Entity("AlgoDuck.Models.TestingResult", b =>
                {
                    b.HasOne("AlgoDuck.Models.TestCase", "TestCase")
                        .WithMany("TestingResults")
                        .HasForeignKey("TestCaseId")
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.UserSolution", "UserSolution")
                        .WithMany("TestingResults")
                        .HasForeignKey("UserSolutionId")
                        .IsRequired();

                    b.Navigation("TestCase");

                    b.Navigation("UserSolution");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserAchievement", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_achievement_user_ref");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserConfig", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithOne("UserConfig")
                        .HasForeignKey("AlgoDuck.Models.UserConfig", "UserId")
                        .IsRequired()
                        .HasConstraintName("user_config_application_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolution", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", "Problem")
                        .WithMany("UserSolutions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_solution_problem_ref");

                    b.HasOne("AlgoDuck.Models.Status", "Status")
                        .WithMany("UserSolutions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_solution_status_ref");

                    b.HasOne("AlgoDuck.Models.ApplicationUser", "User")
                        .WithMany("UserSolutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("solution_user_ref");

                    b.Navigation("Problem");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContestProblem", b =>
                {
                    b.HasOne("AlgoDuck.Models.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contest_problem_contest_ref");

                    b.HasOne("AlgoDuck.Models.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contest_problem_problem_ref");
                });

            modelBuilder.Entity("HasTag", b =>
                {
                    b.HasOne("AlgoDuck.Models.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("has_tag_problem_ref");

                    b.HasOne("AlgoDuck.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("has_tag_tag_ref");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AlgoDuck.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoDuck.Models.ApplicationUser", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("PurchasedTestCases");

                    b.Navigation("Purchases");

                    b.Navigation("Sessions");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserConfig");

                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("AlgoDuck.Models.Category", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("AlgoDuck.Models.Cohort", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AlgoDuck.Models.Difficulty", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("AlgoDuck.Models.EditorTheme", b =>
                {
                    b.Navigation("EditorLayouts");
                });

            modelBuilder.Entity("AlgoDuck.Models.Item", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("AlgoDuck.Models.Problem", b =>
                {
                    b.Navigation("TestCases");

                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("AlgoDuck.Models.Rarity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlgoDuck.Models.Session", b =>
                {
                    b.Navigation("InverseReplacedBySession");
                });

            modelBuilder.Entity("AlgoDuck.Models.Status", b =>
                {
                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("AlgoDuck.Models.TestCase", b =>
                {
                    b.Navigation("PurchasedTestCases");

                    b.Navigation("TestingResults");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserConfig", b =>
                {
                    b.Navigation("EditorLayouts");
                });

            modelBuilder.Entity("AlgoDuck.Models.UserSolution", b =>
                {
                    b.Navigation("TestingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
